# GENERATION
source: "./src/"
destination: ".site/"
url: "http://localhost:4000"

# SITE
email: marcus.hansson@email.com
github: github.com/defavlt
name: "Classico"
url: "http://defavlt.github.io/Classico"
paginate: 5
markdown: rdiscount
permalink: /:title/
pygments: false
