# GENERATION
<<<<<<< HEAD
url: "http://localhost:4000"
permalink: "/:title/"
=======
source: "./src/"
destination: ".site/"
url: "http://defav.lt/Classico"
# url: "http://defavlt.github.io/Classico"

# SITE
email: marcus.hansson@email.com
github: github.com/defavlt
name: "Classico"
paginate: 5
markdown: rdiscount
permalink: /:title/
pygments: false
>>>>>>> 843c327ae5793d03b2552d7b1a6e2568e7b282cb
